version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    command: "tail -f /dev/null"
    volumes:
      - .:/go/src
    working_dir: /go/src

volumes:
  db_data: